services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - '80:80'
    volumes:
      - ./nginx.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend_network

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - APP_DEBUG=True
      - APP_PORT=5000
      - APP_HOST=0.0.0.0
      - SECRET_KEY=R29wZW51eERldmVsb3Blcgo=
    networks:
      - backend_network
      - frontend_network

  microservice:
    build:
      context: ./image-microservice
      dockerfile: Dockerfile
    environment:
      - IMAGE_MICROSERVICE_HOST=image-microservice
      - IMAGE_MICROSERVICE_PORT=3001
    networks:
      - backend_network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - backend_network
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - backend_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
